import{i as c}from"./assets/vendor-8e8cd629.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();function l(n){return n.map(r=>`<li class="photo-item">
        <a href="${r.largeImageURL}"><img class="img-item" src="${r.webformatURL}" alt="${r.tags}"/></a> 
        <div class="descr-wrapper">
        <p class="descr"><span>Likes</span> ${r.likes}</p>
        <p class="descr"><span>Views</span> ${r.views}</p>
        <p class="descr"><span>Comments</span> ${r.comments}</p>
        <p class="descr"><span>Downloads</span> ${r.downloads}</p>
        </div>
      </li>`).join("")}const u=document.querySelector("#searchImg");function m(){const n=new URLSearchParams({key:"45320962-957458a2920d861910609dde6",q:`${u.value}`,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`https://pixabay.com/api/?${n}`).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}const d=document.querySelector("#searchBtn"),i=document.querySelector(".list-images");d.addEventListener("click",n=>{n.preventDefault(),i.innerHTML="",i.innerHTML='<span class="loader"></span>',m().then(t=>{if(t.hits.length===0)c.error({timeout:3e3,position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});else{const r=l(t.hits);i.insertAdjacentHTML("beforeend",r)}}).catch(t=>console.log(t)),setTimeout(()=>{})});
//# sourceMappingURL=commonHelpers.js.map
