import{S as c,i as l}from"./assets/vendor-8c59ed88.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const o=document.querySelector(".list-images");new c(".list-images a",{close:!0});function u(i){const t=i.map(s=>`<li class="photo-item">
        <a href="${s.largeImageURL}"><img class="img-item" src="${s.webformatURL}" alt="${s.tags}"/></a> 
        <div class="descr-wrapper">
        <p class="descr"><span>Likes</span> ${s.likes}</p>
        <p class="descr"><span>Views</span> ${s.views}</p>
        <p class="descr"><span>Comments</span> ${s.comments}</p>
        <p class="descr"><span>Downloads</span> ${s.downloads}</p>
        </div>
      </li>`).join("");o.insertAdjacentHTML("beforeend",t)}function m(){o.innerHTML=""}const d=document.querySelector("#searchImg"),f=document.querySelector("#searchBtn");f.addEventListener("click",i=>{i.preventDefault(),m(),p().then(t=>{t.hits.length===0?l.error({timeout:3e3,position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}):u(t.hits)}).catch(t=>console.log(t))});function p(){const i=new URLSearchParams({key:"45320962-957458a2920d861910609dde6",q:`${d.value}`,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`https://pixabay.com/api/?${i}`).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}
//# sourceMappingURL=commonHelpers.js.map
